# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('FirmaID', models.AutoField(primary_key=True, serialize=False)),
                ('FirmaAdi', models.TextField(max_length=250, verbose_name='Firma Adı')),
                ('FirmaEposta', models.TextField(max_length=250, verbose_name='Firma Eposta')),
                ('FirmaTelefonu', models.TextField(max_length=13, verbose_name='Firma Telefonu')),
                ('FirmaAdresi', models.TextField(verbose_name='Firma Adresi')),
                ('FirmaAktiflik', models.BooleanField(verbose_name='Firma Aktiflik')),
                ('FirmaLisansSuresi', models.IntegerField(null=True, verbose_name='Firma Lisans Süresi')),
                ('FirmaLisansAnahtari', models.TextField(verbose_name='Firma Lisans Anahtarı')),
                ('FirmaKayıtTarihi', models.DateTimeField(default=datetime.datetime(2017, 7, 29, 14, 26, 29, 945709, tzinfo=utc), verbose_name='Firma Kayıt Tarihi')),
                ('FirmaGuncellemeTarihi', models.DateTimeField(default=datetime.datetime(2017, 7, 29, 14, 26, 29, 945943, tzinfo=utc), verbose_name='Firma Guncelleme Tarihi')),
                ('FirmaToplamFiyat', models.TextField(max_length=50, verbose_name='Firma Toplam Fiyat')),
            ],
        ),
    ]
