# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Servis', '0003_auto_20170729_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='FirmaAdresi',
            field=models.TextField(blank=True, verbose_name='Firma Adresi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaEposta',
            field=models.CharField(blank=True, max_length=250, verbose_name='Firma Eposta'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaGuncellemeTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 29, 14, 39, 12, 14058, tzinfo=utc), verbose_name='Firma Guncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaKayıtTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 29, 14, 39, 12, 13821, tzinfo=utc), verbose_name='Firma Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaTelefonu',
            field=models.CharField(blank=True, max_length=13, verbose_name='Firma Telefonu'),
        ),
    ]
