# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Servis', '0010_auto_20170730_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='FirmaLisansBaslangicTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 9, 39, 40, 541237, tzinfo=utc), verbose_name='Firma Kayıt Tarihi'),
        ),
        migrations.AddField(
            model_name='firma',
            name='FirmaLisansBitisTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 9, 39, 40, 541513, tzinfo=utc), verbose_name='Firma Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaGuncellemeTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 9, 39, 40, 541619, tzinfo=utc), verbose_name='Firma Guncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaKayıtTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 9, 39, 40, 541569, tzinfo=utc), verbose_name='Firma Kayıt Tarihi'),
        ),
    ]
