# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Servis', '0011_auto_20170730_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='FirmaGuncellemeTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 9, 43, 41, 28173, tzinfo=utc), verbose_name='Firma Guncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaKayıtTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 9, 43, 41, 28151, tzinfo=utc), verbose_name='Firma Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaLisansBaslangicTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 9, 43, 41, 27932, tzinfo=utc), verbose_name='Firma Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaLisansBitisTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 9, 43, 41, 28125, tzinfo=utc), verbose_name='Firma Kayıt Tarihi'),
        ),
    ]
