# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Servis', '0013_auto_20170730_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='FirmaGuncellemeTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 13, 50, 10, 929348, tzinfo=utc), verbose_name='Firma Guncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaKayıtTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 13, 50, 10, 929322, tzinfo=utc), verbose_name='Firma Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaLisansBaslangicTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 13, 50, 10, 929045, tzinfo=utc), verbose_name='Firma Lisans Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaLisansBitisTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 13, 50, 10, 929286, tzinfo=utc), verbose_name='Firma Lisans bitiş Tarihi'),
        ),
    ]
