# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Servis', '0014_auto_20170730_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='FirmaLisansKayitSayisi',
            field=models.IntegerField(default=0, verbose_name='Firma Lisans Kayıt Sayısı'),
        ),
        migrations.AddField(
            model_name='firma',
            name='FirmaLisansSayisi',
            field=models.IntegerField(default=1, verbose_name='Firma Lisans Sayısı'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaGuncellemeTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 13, 51, 5, 578191, tzinfo=utc), verbose_name='Firma Guncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaKayıtTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 13, 51, 5, 578144, tzinfo=utc), verbose_name='Firma Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaLisansBaslangicTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 13, 51, 5, 577725, tzinfo=utc), verbose_name='Firma Lisans Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='FirmaLisansBitisTarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 13, 51, 5, 578035, tzinfo=utc), verbose_name='Firma Lisans bitiş Tarihi'),
        ),
    ]
